<?php

namespace AppBundle\Repository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * MovieRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $page
     * @param int $max_per_page
     * @param $order_by
     * @param $order_by_direction
     *
     * @return Pagerfanta
     */
    public function getPaginated($page, $max_per_page, $order_by, $order_by_direction)
    {
        $qb = $this->createQueryBuilder('m')

        ;

        $adapter = new DoctrineORMAdapter($qb);
        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setMaxPerPage($max_per_page);
        $pagerfanta->setCurrentPage($page);

        if (in_array($order_by_direction, ['asc', 'desc'])) {
            $qb->orderBy('m.'.$order_by, $order_by_direction);
        }

        return $pagerfanta;
    }
}
